# Generated by Django 4.0.5 on 2022-08-08 10:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AutoBatirApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='ApprovedBy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ArchivedPermit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ConstructionPlan', models.FileField(upload_to='docs_const_plan/pdfs/')),
                ('LandOwnerShipDoc', models.FileField(blank=True, null=True, upload_to='docs_landownership/pdfs/')),
                ('OtherDoc', models.FileField(blank=True, null=True, upload_to='docs_other/pdfs/')),
                ('MainZonecode', models.CharField(blank=True, max_length=25, null=True)),
                ('Date', models.DateTimeField()),
                ('Status', models.CharField(blank=True, default='pending', max_length=10, null=True)),
                ('ApprovedBy', models.CharField(blank=True, max_length=10, null=True)),
                ('updated_at_issuedDate', models.DateTimeField()),
                ('UPI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AutoBatirApp.upi', verbose_name='UPI related to permit')),
                ('registration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoBatirApp.registration')),
            ],
        ),
    ]
