# Generated by Django 4.0.5 on 2022-08-14 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoBatirApp', '0002_permit_approvedby_archivedpermit'),
    ]

    operations = [
        migrations.AddField(
            model_name='upi',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upi',
            name='NationalID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AutoBatirApp.nationalid'),
        ),
    ]
