# Generated by Django 4.0.5 on 2022-08-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoBatirApp', '0003_upi_user_alter_upi_nationalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='personal_National_Id',
        ),
    ]
