# Generated by Django 4.0.5 on 2022-08-19 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AutoBatirApp', '0004_remove_registration_personal_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedpermit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
