# Generated by Django 4.0.5 on 2022-08-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoBatirApp', '0005_alter_archivedpermit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedpermit',
            name='ApprovedBy',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='ApprovedBy',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
