# Generated by Django 4.0.5 on 2022-08-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoBatirApp', '0006_alter_archivedpermit_approvedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='ConstructionPlan',
            field=models.FileField(blank=True, null=True, upload_to='docs_const_plan/pdfs/'),
        ),
    ]
