# Generated by Django 4.0.5 on 2022-08-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoBatirApp', '0008_alter_permit_constructionplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationalid',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='nationalid',
            name='Gender',
        ),
        migrations.AddField(
            model_name='nationalid',
            name='Address_street',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='nationalid',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='permit',
            name='MainZonecode',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
