# Generated by Django 4.1 on 2022-09-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoBatirApp', '0010_alter_upi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='NationalID',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
