# Generated by Django 4.1 on 2022-09-05 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ('AutoBatirApp', '0013_alter_upi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='NationalID',
            field=models.IntegerField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='National_id',
            field=models.IntegerField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='NationalID',
            field=models.IntegerField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.query.prefetch_related_objects, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upi',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
