# Generated by Django 4.1 on 2022-09-05 11:44

import AutoBatirApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoBatirApp', '0014_alter_engineer_nationalid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='NationalID',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='National_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='NationalID',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upi',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(AutoBatirApp.models.User), to=settings.AUTH_USER_MODEL),
        ),
    ]
