# Generated by Django 4.1 on 2022-09-05 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoBatirApp', '0015_alter_engineer_nationalid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upi',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
