# Generated by Django 4.1 on 2022-09-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoBatirApp', '0018_alter_upi_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedpermit',
            name='Paymentproof',
            field=models.FileField(blank=True, null=True, upload_to='Bankslip/pdfs/'),
        ),
        migrations.AddField(
            model_name='permit',
            name='Paymentproof',
            field=models.FileField(blank=True, null=True, upload_to='Bankslip/pdfs/'),
        ),
    ]
